spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  h2:
    console:
      enabled: false

stempelkarte:
  base-url: ${APP_BASE_URL:https://stempelkarte-backend.onrender.com}
  google:
    issuer-id: ${GOOGLE_ISSUER_ID:3388000000023146979}
    class-suffix: stempelkarte_class_v1
    service-account-path: ${GOOGLE_SA_PATH:/etc/secrets/google-wallet-key.json}