spring:
  jpa:
    open-in-view: false
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  threads:
    virtual:
      enabled: true

stempelkarte:
  reward-threshold: 10
  jwt-secret: ${JWT_SECRET:stempelkarte-super-secret-key-mindestens-32-zeichen-lang}
  admin-secret: ${ADMIN_SECRET:admin-geheim-nur-lokal}
  upload-path: ${UPLOAD_PATH:./uploads}
  base-url: ${APP_BASE_URL:http://localhost:8080}

  apple:
    pass-type-identifier: ${APPLE_PASS_TYPE_ID:pass.com.cafeespresso.stempelkarte}
    team-identifier: ${APPLE_TEAM_ID:ABCDE12345}
    organization-name: Cafe Espresso
    cert-path: ${APPLE_CERT_PATH:./certs/PassCertificate.p12}
    cert-password: ${APPLE_CERT_PASSWORD:changeit}
    wwdr-cert-path: ${APPLE_WWDR_PATH:./certs/AppleWWDRCAG4.pem}
    template-path: ${APPLE_TEMPLATE_PATH:./pass-template/StempelKarte.pass}
    auth-secret: ${APPLE_AUTH_SECRET:bitte-im-prod-aendern-mindestens-32-zeichen}

  google:
    issuer-id: 3388000000023146979
    class-suffix: stempelkarte_class_v1
    service-account-path: C:/Users/adham/Downloads/stempelkarte-496400-8da6689f7402.json

  apns:
    enabled: ${APNS_ENABLED:false}
    key-id: ${APNS_KEY_ID:}
    team-id: ${APPLE_TEAM_ID:ABCDE12345}
    auth-key-path: ${APNS_KEY_PATH:./certs/AuthKey.p8}
    use-sandbox: ${APNS_SANDBOX:false}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dzu73ui9i}
  api-key: ${CLOUDINARY_API_KEY:587366334988363}
  api-secret: ${CLOUDINARY_API_SECRET:}
